# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S3gIMr7WR6-mtoYtP3bushmJQ_TX-CUW
"""

import random

characters = ['1','2','3','4','5','6','7','8','9','0','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z',
              'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','<','>','*','(',')','$','+','-','_','%','°',';',':',
              '.','?','!']


number_of_characters = int(input("How many characters should your password have ?"))

for x in range(0,number_of_characters):
  character_random = random.choice(characters)
  print(character_random)